export const NAVIGATION = {
    MAIN_TABS: 'MainTabs',
    SPLASH_SCREEN: 'SplashScreen',
    WELCOME_SCREEN: 'WelcomeScreen',
    LOGIN_SCREEN: 'LoginScreen',
    SIGN_UP_SCREEN: 'SignupScreen',
    FORGOT_PASSWORD_SCREEN: 'ForgotPasswordScreen',
    ONBOARDING_STEPS: 'OnboardingScreen',
    MOOD_SCREEN: 'MoodScreen',
    ABOUT_US_SCREEN: 'AboutUsScreen',
    PRICING_SCREEN: 'PricingScreen',
    PRIVACY_POLICY_SCREEN: 'PrivacyPolicyScreen',
    TERMS_OF_SERVICE_SCREEN: 'TermsOfServiceScreen',
    ACCOUNT_DELETION_SCREEN: 'AccountDeletionScreen',
    EXPERT_CONSULTATION_SCREEN: 'ExpertConsultationScreen',
    JOURNAL_WRITING_SCREEN: 'JournalWritingScreen',
    HOME_TAB: 'Home',
    DASHBOARD_TAB: 'Dashboard',
    CHAT_TAB: 'Chat',
    JOURNAL_TAB: 'Journal',
    PROFILE_TAB: 'Profile',
} as const;